@ECHO OFF
chcp 65001
CD /D "%~dp0\.."
CLS
SET PHP=%PROGRAMFILES%\AVE-UTILITIES\php\8.3
IF NOT EXIST "%PROGRAMFILES%\AVE-UTILITIES\core\1.1.0" ECHO.&ECHO AVE-UTILITIES AVE-PHP is required&ECHO.&PAUSE>nul&EXIT
IF NOT EXIST "%PROGRAMFILES%\AVE-UTILITIES\imagick" ECHO.&ECHO AVE-UTILITIES AVE-PHP is required&ECHO.&PAUSE>nul&EXIT
IF NOT EXIST "%PHP%" ECHO.&ECHO AVE-UTILITIES PHP 8.3 is required&ECHO.&PAUSE>nul&EXIT
SET PATH=%PATH%;%PHP%;%PROGRAMFILES%\AVE-UTILITIES\core\1.1.0;%PROGRAMFILES%\AVE-UTILITIES\imagick
"%PHP%\php.exe" "%CD%\includes\main.php" --make-backup "%~1"
GOTO :eof